# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build/CMakeFiles /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build/src/CMakeFiles/progress.marks
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f CMakeFiles/Makefile2 src/all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f CMakeFiles/Makefile2 src/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/CMakeFiles/42sh.dir/rule:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f CMakeFiles/Makefile2 src/CMakeFiles/42sh.dir/rule
.PHONY : src/CMakeFiles/42sh.dir/rule

# Convenience name for target.
42sh: src/CMakeFiles/42sh.dir/rule

.PHONY : 42sh

# fast build rule for target.
42sh/fast:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/build
.PHONY : 42sh/fast

builtins/boolean.o: builtins/boolean.c.o

.PHONY : builtins/boolean.o

# target to build an object file
builtins/boolean.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/builtins/boolean.c.o
.PHONY : builtins/boolean.c.o

builtins/boolean.i: builtins/boolean.c.i

.PHONY : builtins/boolean.i

# target to preprocess a source file
builtins/boolean.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/builtins/boolean.c.i
.PHONY : builtins/boolean.c.i

builtins/boolean.s: builtins/boolean.c.s

.PHONY : builtins/boolean.s

# target to generate assembly for a file
builtins/boolean.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/builtins/boolean.c.s
.PHONY : builtins/boolean.c.s

builtins/echo.o: builtins/echo.c.o

.PHONY : builtins/echo.o

# target to build an object file
builtins/echo.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/builtins/echo.c.o
.PHONY : builtins/echo.c.o

builtins/echo.i: builtins/echo.c.i

.PHONY : builtins/echo.i

# target to preprocess a source file
builtins/echo.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/builtins/echo.c.i
.PHONY : builtins/echo.c.i

builtins/echo.s: builtins/echo.c.s

.PHONY : builtins/echo.s

# target to generate assembly for a file
builtins/echo.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/builtins/echo.c.s
.PHONY : builtins/echo.c.s

evalxpr/evalxpr.o: evalxpr/evalxpr.c.o

.PHONY : evalxpr/evalxpr.o

# target to build an object file
evalxpr/evalxpr.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/evalxpr.c.o
.PHONY : evalxpr/evalxpr.c.o

evalxpr/evalxpr.i: evalxpr/evalxpr.c.i

.PHONY : evalxpr/evalxpr.i

# target to preprocess a source file
evalxpr/evalxpr.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/evalxpr.c.i
.PHONY : evalxpr/evalxpr.c.i

evalxpr/evalxpr.s: evalxpr/evalxpr.c.s

.PHONY : evalxpr/evalxpr.s

# target to generate assembly for a file
evalxpr/evalxpr.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/evalxpr.c.s
.PHONY : evalxpr/evalxpr.c.s

evalxpr/fifo.o: evalxpr/fifo.c.o

.PHONY : evalxpr/fifo.o

# target to build an object file
evalxpr/fifo.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/fifo.c.o
.PHONY : evalxpr/fifo.c.o

evalxpr/fifo.i: evalxpr/fifo.c.i

.PHONY : evalxpr/fifo.i

# target to preprocess a source file
evalxpr/fifo.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/fifo.c.i
.PHONY : evalxpr/fifo.c.i

evalxpr/fifo.s: evalxpr/fifo.c.s

.PHONY : evalxpr/fifo.s

# target to generate assembly for a file
evalxpr/fifo.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/fifo.c.s
.PHONY : evalxpr/fifo.c.s

evalxpr/help_evalxpr.o: evalxpr/help_evalxpr.c.o

.PHONY : evalxpr/help_evalxpr.o

# target to build an object file
evalxpr/help_evalxpr.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/help_evalxpr.c.o
.PHONY : evalxpr/help_evalxpr.c.o

evalxpr/help_evalxpr.i: evalxpr/help_evalxpr.c.i

.PHONY : evalxpr/help_evalxpr.i

# target to preprocess a source file
evalxpr/help_evalxpr.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/help_evalxpr.c.i
.PHONY : evalxpr/help_evalxpr.c.i

evalxpr/help_evalxpr.s: evalxpr/help_evalxpr.c.s

.PHONY : evalxpr/help_evalxpr.s

# target to generate assembly for a file
evalxpr/help_evalxpr.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/help_evalxpr.c.s
.PHONY : evalxpr/help_evalxpr.c.s

evalxpr/ope_evalxpr.o: evalxpr/ope_evalxpr.c.o

.PHONY : evalxpr/ope_evalxpr.o

# target to build an object file
evalxpr/ope_evalxpr.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/ope_evalxpr.c.o
.PHONY : evalxpr/ope_evalxpr.c.o

evalxpr/ope_evalxpr.i: evalxpr/ope_evalxpr.c.i

.PHONY : evalxpr/ope_evalxpr.i

# target to preprocess a source file
evalxpr/ope_evalxpr.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/ope_evalxpr.c.i
.PHONY : evalxpr/ope_evalxpr.c.i

evalxpr/ope_evalxpr.s: evalxpr/ope_evalxpr.c.s

.PHONY : evalxpr/ope_evalxpr.s

# target to generate assembly for a file
evalxpr/ope_evalxpr.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/evalxpr/ope_evalxpr.c.s
.PHONY : evalxpr/ope_evalxpr.c.s

free_lexer.o: free_lexer.c.o

.PHONY : free_lexer.o

# target to build an object file
free_lexer.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/free_lexer.c.o
.PHONY : free_lexer.c.o

free_lexer.i: free_lexer.c.i

.PHONY : free_lexer.i

# target to preprocess a source file
free_lexer.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/free_lexer.c.i
.PHONY : free_lexer.c.i

free_lexer.s: free_lexer.c.s

.PHONY : free_lexer.s

# target to generate assembly for a file
free_lexer.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/free_lexer.c.s
.PHONY : free_lexer.c.s

help_parser.o: help_parser.c.o

.PHONY : help_parser.o

# target to build an object file
help_parser.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/help_parser.c.o
.PHONY : help_parser.c.o

help_parser.i: help_parser.c.i

.PHONY : help_parser.i

# target to preprocess a source file
help_parser.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/help_parser.c.i
.PHONY : help_parser.c.i

help_parser.s: help_parser.c.s

.PHONY : help_parser.s

# target to generate assembly for a file
help_parser.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/help_parser.c.s
.PHONY : help_parser.c.s

lexer.o: lexer.c.o

.PHONY : lexer.o

# target to build an object file
lexer.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/lexer.c.o
.PHONY : lexer.c.o

lexer.i: lexer.c.i

.PHONY : lexer.i

# target to preprocess a source file
lexer.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/lexer.c.i
.PHONY : lexer.c.i

lexer.s: lexer.c.s

.PHONY : lexer.s

# target to generate assembly for a file
lexer.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/lexer.c.s
.PHONY : lexer.c.s

lexer3.o: lexer3.c.o

.PHONY : lexer3.o

# target to build an object file
lexer3.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/lexer3.c.o
.PHONY : lexer3.c.o

lexer3.i: lexer3.c.i

.PHONY : lexer3.i

# target to preprocess a source file
lexer3.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/lexer3.c.i
.PHONY : lexer3.c.i

lexer3.s: lexer3.c.s

.PHONY : lexer3.s

# target to generate assembly for a file
lexer3.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/lexer3.c.s
.PHONY : lexer3.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/main.c.s
.PHONY : main.c.s

new_lexer.o: new_lexer.c.o

.PHONY : new_lexer.o

# target to build an object file
new_lexer.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/new_lexer.c.o
.PHONY : new_lexer.c.o

new_lexer.i: new_lexer.c.i

.PHONY : new_lexer.i

# target to preprocess a source file
new_lexer.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/new_lexer.c.i
.PHONY : new_lexer.c.i

new_lexer.s: new_lexer.c.s

.PHONY : new_lexer.s

# target to generate assembly for a file
new_lexer.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/new_lexer.c.s
.PHONY : new_lexer.c.s

parcours.o: parcours.c.o

.PHONY : parcours.o

# target to build an object file
parcours.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parcours.c.o
.PHONY : parcours.c.o

parcours.i: parcours.c.i

.PHONY : parcours.i

# target to preprocess a source file
parcours.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parcours.c.i
.PHONY : parcours.c.i

parcours.s: parcours.c.s

.PHONY : parcours.s

# target to generate assembly for a file
parcours.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parcours.c.s
.PHONY : parcours.c.s

parcours2.o: parcours2.c.o

.PHONY : parcours2.o

# target to build an object file
parcours2.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parcours2.c.o
.PHONY : parcours2.c.o

parcours2.i: parcours2.c.i

.PHONY : parcours2.i

# target to preprocess a source file
parcours2.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parcours2.c.i
.PHONY : parcours2.c.i

parcours2.s: parcours2.c.s

.PHONY : parcours2.s

# target to generate assembly for a file
parcours2.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parcours2.c.s
.PHONY : parcours2.c.s

parcours3.o: parcours3.c.o

.PHONY : parcours3.o

# target to build an object file
parcours3.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parcours3.c.o
.PHONY : parcours3.c.o

parcours3.i: parcours3.c.i

.PHONY : parcours3.i

# target to preprocess a source file
parcours3.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parcours3.c.i
.PHONY : parcours3.c.i

parcours3.s: parcours3.c.s

.PHONY : parcours3.s

# target to generate assembly for a file
parcours3.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parcours3.c.s
.PHONY : parcours3.c.s

parser.o: parser.c.o

.PHONY : parser.o

# target to build an object file
parser.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parser.c.o
.PHONY : parser.c.o

parser.i: parser.c.i

.PHONY : parser.i

# target to preprocess a source file
parser.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parser.c.i
.PHONY : parser.c.i

parser.s: parser.c.s

.PHONY : parser.s

# target to generate assembly for a file
parser.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/parser.c.s
.PHONY : parser.c.s

redirection.o: redirection.c.o

.PHONY : redirection.o

# target to build an object file
redirection.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/redirection.c.o
.PHONY : redirection.c.o

redirection.i: redirection.c.i

.PHONY : redirection.i

# target to preprocess a source file
redirection.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/redirection.c.i
.PHONY : redirection.c.i

redirection.s: redirection.c.s

.PHONY : redirection.s

# target to generate assembly for a file
redirection.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/redirection.c.s
.PHONY : redirection.c.s

shell_parser.o: shell_parser.c.o

.PHONY : shell_parser.o

# target to build an object file
shell_parser.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/shell_parser.c.o
.PHONY : shell_parser.c.o

shell_parser.i: shell_parser.c.i

.PHONY : shell_parser.i

# target to preprocess a source file
shell_parser.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/shell_parser.c.i
.PHONY : shell_parser.c.i

shell_parser.s: shell_parser.c.s

.PHONY : shell_parser.s

# target to generate assembly for a file
shell_parser.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/shell_parser.c.s
.PHONY : shell_parser.c.s

tool_parser.o: tool_parser.c.o

.PHONY : tool_parser.o

# target to build an object file
tool_parser.c.o:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/tool_parser.c.o
.PHONY : tool_parser.c.o

tool_parser.i: tool_parser.c.i

.PHONY : tool_parser.i

# target to preprocess a source file
tool_parser.c.i:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/tool_parser.c.i
.PHONY : tool_parser.c.i

tool_parser.s: tool_parser.c.s

.PHONY : tool_parser.s

# target to generate assembly for a file
tool_parser.c.s:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(MAKE) -f src/CMakeFiles/42sh.dir/build.make src/CMakeFiles/42sh.dir/tool_parser.c.s
.PHONY : tool_parser.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... 42sh"
	@echo "... builtins/boolean.o"
	@echo "... builtins/boolean.i"
	@echo "... builtins/boolean.s"
	@echo "... builtins/echo.o"
	@echo "... builtins/echo.i"
	@echo "... builtins/echo.s"
	@echo "... evalxpr/evalxpr.o"
	@echo "... evalxpr/evalxpr.i"
	@echo "... evalxpr/evalxpr.s"
	@echo "... evalxpr/fifo.o"
	@echo "... evalxpr/fifo.i"
	@echo "... evalxpr/fifo.s"
	@echo "... evalxpr/help_evalxpr.o"
	@echo "... evalxpr/help_evalxpr.i"
	@echo "... evalxpr/help_evalxpr.s"
	@echo "... evalxpr/ope_evalxpr.o"
	@echo "... evalxpr/ope_evalxpr.i"
	@echo "... evalxpr/ope_evalxpr.s"
	@echo "... free_lexer.o"
	@echo "... free_lexer.i"
	@echo "... free_lexer.s"
	@echo "... help_parser.o"
	@echo "... help_parser.i"
	@echo "... help_parser.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... lexer3.o"
	@echo "... lexer3.i"
	@echo "... lexer3.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... new_lexer.o"
	@echo "... new_lexer.i"
	@echo "... new_lexer.s"
	@echo "... parcours.o"
	@echo "... parcours.i"
	@echo "... parcours.s"
	@echo "... parcours2.o"
	@echo "... parcours2.i"
	@echo "... parcours2.s"
	@echo "... parcours3.o"
	@echo "... parcours3.i"
	@echo "... parcours3.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... redirection.o"
	@echo "... redirection.i"
	@echo "... redirection.s"
	@echo "... shell_parser.o"
	@echo "... shell_parser.i"
	@echo "... shell_parser.s"
	@echo "... tool_parser.o"
	@echo "... tool_parser.i"
	@echo "... tool_parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /mnt/c/Users/toddt/42sh/epita-ing-assistants-acu-42sh-2025-lyon-27/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

